# Generated by Django 6.1.1 on 2026-09-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='about',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
